---
title: "이희철"
author: "heechul"
date: '2019 6 11 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(KoNLP)
library(wordcloud)
useSejongDic()
library(RColorBrewer)
library(stringr)
```

##### WordCloud 연습문제

```{r}

reply <- readLines('응답소_2015.txt')
reply2 <- sapply(reply, extractNoun, USE.NAMES = F)
head(unlist(reply2), 30)
cdata <- unlist(reply2)
reply2 <- str_replace_all(cdata, '[^[:alpha:]]', '')
reply2 <- gsub(' ','', reply2)


txt <- readLines('응답했니gsub.txt')
cnt_txt <- length(txt)
i <- 1
for(i in 1:cnt_txt) {
  reply2 <- gsub((txt[i]),'',reply2)
}
reply2 <- Filter(function(x){nchar(x) >= 2 & nchar(x) <=7}, reply2)
write(unlist(reply2), 'reply_2.txt')
rev <- read.table('reply_2.txt')
nrow(rev)


wordcount <- table(rev)
head(sort(wordcount, decreasing = T), 100)

palete <- brewer.pal(9, 'RdBu')
wordcloud(names(wordcount), freq = wordcount, scale=c(3,1), rot.per = 0.1, min.freq = 100,
          random.order = F, random.color = T, colors = palete)
legend(0.2, 0.9,'2015년도 응답소의 질문 빈도', cex=0.8, fill=NA, border=NA, bg='white', 
       text.col='red', text.font=1, box.col='red')
```