---
title: "이희철"
author: "heechul"
date: '2019 6 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
```

##### ggplot / R Markdown 연습문제

### 문제 1
```{r mpg}
mpg01 <- mpg %>%
  select(cty, hwy)

plot(mpg01, main='cty와 hwy의 산점도', col=c('blue', 'red'), xlim=c(5,38), ylim=c(10,45))
legend(5, 45, c('cty', 'hwy'), cex = 0.7, col =c('blue','red'),pch=1)
```
<br><br>

### 문제 2
```{r midwest}
midwest2 <- midwest %>%
  select(poptotal, popasian) %>%
  filter(poptotal<=500000, popasian<=10000)

plot(midwest2, main='poptotal와 popasian의 산점도', col=c('blue', 'red'), xlim=c(0,500000), ylim=c(0,10000))
legend(100, 9500, c('poptotal', 'popasian'), cex = 0.5, col =c('blue','red'),pch=1)
```
<br><br>

### 문제 3 
```{r}
mpg3 <- mpg %>%
  group_by(manufacturer) %>%
  filter(class=='suv') %>%
  select(manufacturer, class, cty) %>%
  summarise_each(funs(mean), cty) %>%
  arrange(desc(cty)) %>%
  head(5)

ggplot(mpg3, aes(x=reorder(manufacturer, -cty), y=cty)) +
  geom_col()
```
<br><br>

### 문제 4
```{r}
mpg4 <- mpg %>% 
  group_by(class) %>% 
  tally()
mpg44 <- select(mpg4, n)
mpg44 <- t(mpg44)

barplot(mpg44, main='Class', col='green',
        names=c('2seater', 'compact', 'minsize', 'minivan', 'pickup', 'subcompact', 'suv'))
```
<br><br> 
  
### 문제 5
```{r}
economics <- economics %>%
  select(date, psavert)

ggplot(economics, aes(x=date, y=psavert)) +
         geom_line()

```
<br><br>


### 문제 6
```{r}
mpg6 <- mpg %>%
  filter(class %in% c("compact", "subcompact", "suv"))
ggplot(mpg6, aes(x=class, y=cty,)) +
  geom_boxplot()
```
<br><br>

### 문제 7
##7-1
```{r diamonds}
ggplot(diamonds, aes(x=cut)) +
  geom_bar()
```
<br><br>

##7-2
```{r}
diamonds7_2 <- diamonds %>%
  group_by(cut) %>%
  summarise_each(funs(mean), price)
  
ggplot(diamonds7_2, aes(x=cut, y=price,)) +
  geom_col()
```
<br><br>

##7-3
```{r}
diamonds7_3 <- diamonds %>%
  group_by(color) %>%
  summarise_each(funs(mean), price)

diamonds7_4 <- diamonds %>%
  group_by(cut) %>%
  summarise_each(funs(mean), price)

par(mfrow=c(1,2))
ggplot(diamonds7_3, aes(x=color, y=price)) +
  geom_col()

ggplot(diamonds7_4, aes(x=cut, y=price)) +
  geom_col()

```
<br>