setwd('D:/Heechul/R/R_Lecture/part2/stage3/Ex3-2')
install.packages('KoNLP')
install.packages('wordcloud')
install.packages('stringr')
library(KoNLP)
library(wordcloud)
library(stringr)
library(ggplot2)
library(dplyr)
library(plyr)
install.packages('reshape')
library(reshape)
useSejongDic()

